FROM python:3.11-slim

WORKDIR /app

COPY requirements.api.txt .
COPY requirements.test.txt .
RUN pip install --no-cache-dir -r requirements.api.txt -r requirements.test.txt

COPY app ./app
COPY cli.py .
COPY tests ./tests

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]